name = "ScTenifoldNet"
uuid = "8707e194-616b-4c04-957e-bf382f698cfa"
authors = ["James Cai <jcai@tamu.edu>"]
version = "0.0.1"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
MultipleTesting = "f8716d33-7c4a-5097-896f-ce0ecbd3ef6b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TSVD = "9449cd9e-2762-5aa3-a617-5413e99d722e"
TensorToolbox = "9c690861-8ade-587a-897e-15364bc6f718"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

["0.0.1"]
julia = "1.4.2"
Distributions = "0.23.4"
MultipleTesting = "0.4.1"
TSVD = "0.4.0"
TensorToolbox = "1.0.1"
